#-------------------------------
# General Site Settings
title: BeiteZhu
# logo: beite_logo.webp # You can add own logo.
description: Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Alex Rodriguez
  image: sakura11.jpeg
  say-hello: Hello, I’m <strong>Beite Zhu</strong>
  bio: a product manager and marketing professional with 7 years of experience in the tech industry. I have successfully designed and launched app and SaaS products. Expertise in Product Management, Market Survey, and Marketing Strategy (including Growth Marketing and Product Marketing) for both B2B and B2C products.

#-------------------------------
# Contact links
Linkedin: https://www.linkedin.com/in/beite-zhu/



#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
